=== TigrisEuphrates/Xml_task2/Xml_task/hardware.dtd
<!ELEMENT hardware (CPUs,GCards,SSDs)>
<!ELEMENT CPUs (CPU*)>
<!ELEMENT CPU (name,price)>
<!ATTLIST CPU on_sale CDATA #REQUIRED>
<!ATTLIST CPU recommended CDATA #IMPLIED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT price (#PCDATA)>

<!ELEMENT GCards (Graphics_Card*)>
<!ELEMENT Graphics_Card (name,price)>
<!ATTLIST Graphics_Card on_sale CDATA #REQUIRED>
<!ATTLIST Graphics_Card recommended CDATA #IMPLIED>

<!ELEMENT SSDs (SSD*)>
<!ELEMENT SSD (name,price)>
<!ATTLIST SSD on_sale CDATA #REQUIRED>
<!ATTLIST SSD recommended CDATA #IMPLIED>

=== TigrisEuphrates/Xml_task2/Xml_task/hardware.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE hardware SYSTEM "hardware.dtd">
<hardware>
	<CPUs>
		<CPU on_sale="true">
			<name>Intel Core i5 10400F</name>
			<price>165.00</price>
		</CPU>
		<CPU on_sale="false" recommended="true">
			<name>Intel Core i5 11400F</name>
			<price>173.00</price>
		</CPU>
		<CPU on_sale="false">
			<name>Intel Core i3 10100F</name>
			<price>107.00</price>
		</CPU>
		<CPU on_sale="false" recommended="true">
			<name>AMD Ryzen 5 3600</name>
			<price>199.00</price>
		</CPU>
		<CPU on_sale="true">
			<name>AMD Ryzen 5 2600</name>
			<price>246.37</price>
		</CPU>
		<CPU on_sale="true">
			<name>AMD Ryzen 7 4700G</name>
			<price>239.99</price>
		</CPU>
	</CPUs>
	<GCards>
		<Graphics_Card on_sale="true" recommended="true">
			<name>ASUS NVIDIA GeForce GTX 1660 Ti TUF EVO Overclocked</name>
			<price>229.99</price>
		</Graphics_Card>
		<Graphics_Card on_sale="false">
			<name>MSI NVIDIA GeForce GTX 1650 Ventus XS Overclocked</name>
			<price>220.99</price>
		</Graphics_Card>
		<Graphics_Card on_sale="true">
			<name>Gigabyte NVIDIA GeForce RTX 3060 Ti EAGLE Overclocked</name>
			<price>449.99</price>
		</Graphics_Card>
		<Graphics_Card on_sale="false">
			<name>Visiontek AMD Radeon RX 560</name>
			<price>199.99</price>
		</Graphics_Card>
		<Graphics_Card on_sale="false">
			<name>Sapphire Technology AMD Radeon RX 5700 XT Nitro Plus</name>
			<price>338.39</price>
		</Graphics_Card>
		<Graphics_Card on_sale="false">
			<name>ASUS AMD Radeon RX 6500 XT Dual Overclocked</name>
			<price>229.99</price>
		</Graphics_Card>
	</GCards>
	<SSDs>
		<SSD on_sale="true">
			<name>Samsung 970 EVO Plus SSD 2TB M.2 NVMe</name>
			<price>189.99</price>
		</SSD>
		<SSD on_sale="true" recommended="true">
			<name>Samsung 980 Pro SSD 1TB M.2 NVMe</name>
			<price>129.99</price>
		</SSD>
		<SSD on_sale="true" recommended="true">
			<name>Inland Professional 512GB SSD</name>
			<price>24.99</price>
		</SSD>
		<SSD on_sale="false">
			<name>Seagate IronWolf 125 4TB SSD</name>
			<price>579.99</price>
		</SSD>
		<SSD on_sale="false">
			<name>WD Black SN850X 1TB NVMe M.2</name>
			<price>119.99</price>
		</SSD>
	</SSDs>
</hardware>
